# Generated by Django 3.2.23 on 2024-04-19 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_product_category_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_2',
        ),
        migrations.DeleteModel(
            name='Category2',
        ),
    ]
