# Generated by Django 3.2.23 on 2024-04-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_auto_20240419_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classtw0',
            name='class_one',
        ),
        migrations.DeleteModel(
            name='ClassOne',
        ),
        migrations.DeleteModel(
            name='ClassTw0',
        ),
    ]
